modLoader = "javafml"
# The loader version doesn't matter. Modify the Forge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${vanillin_id}"
version = "${vanillin_version}"
displayName = "${vanillin_name}"
description = "${vanillin_description}"
logoFile = "logo.png"
authors = "Jozufozu, PepperCode1"
displayURL = "${mod_homepage}"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${ vanillin_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_maven_version_range}"
side = "CLIENT"

[[dependencies.${ vanillin_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
side = "CLIENT"

[[dependencies.${ vanillin_id }]]
modId = "${flywheel_id}"
type = "required"
versionRange = "${flywheel_maven_version_range}"
side = "CLIENT"
